import fs from "fs";
import path from "path";
import type { DashboardReportData } from "@/lib/dashboard-report-data";

// Load pdfkit at runtime (not webpack-bundled) so font AFM files resolve correctly
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require("pdfkit") as typeof import("pdfkit");

export type ExportMeta = {
  tab: string;
  rangeLabel: string;
  franchiseLabel: string;
  generatedBy: string;
  statusLabel?: string;
  orgName?: string;
  orgTagline?: string;
};

const BRAND = {
  name: "IVESDC",
  fullName: "Institute of Vocational Education & Skill Development Council",
  tagline: "Management System · Dashboard Report",
  primary: "#1E4A85",
  gold: "#C4A35A",
  muted: "#64748B",
  border: "#CBD5E1",
  soft: "#F1F5F9",
};

const TAB_TITLES: Record<string, string> = {
  overview: "Overview Report",
  analytics: "Analytics Report",
  activity: "Activity Report",
};

function tabTitle(tab: string) {
  return TAB_TITLES[tab] || "Dashboard Report";
}

function money(n: number) {
  return `₹${Number(n || 0).toLocaleString("en-IN", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  })}`;
}

function moneyPlain(n: number) {
  return Number(Number(n || 0).toFixed(2));
}

function fmtDate(iso: string) {
  try {
    return new Date(iso).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return iso.slice(0, 10);
  }
}

function fmtDateTime(d = new Date()) {
  return d.toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });
}

function titleCase(s: string) {
  return s
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function escapeXml(s: string) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function resolveLogoPath() {
  const candidates = [
    path.join(process.cwd(), "public", "logo", "IVESDC LOGO-07.png"),
    path.join(process.cwd(), "public", "logo", "IVESDC LOGO-01.png"),
    path.join(process.cwd(), "public", "logo", "IVESDC LOGO-05.png"),
  ];
  return candidates.find((p) => fs.existsSync(p)) || null;
}

type Cell = string | number;

function cellXml(value: Cell, style?: string) {
  const isNum = typeof value === "number" && Number.isFinite(value);
  const styleAttr = style ? ` ss:StyleID="${style}"` : "";
  return `<Cell${styleAttr}><Data ss:Type="${isNum ? "Number" : "String"}">${escapeXml(String(value))}</Data></Cell>`;
}

function rowXml(cells: Cell[], styles?: (string | undefined)[]) {
  return `<Row>${cells.map((c, i) => cellXml(c, styles?.[i])).join("")}</Row>`;
}

function emptyRow(cols = 2) {
  return rowXml(Array(cols).fill(""));
}

/** Professional multi-sheet Excel (SpreadsheetML) with branded header */
export function buildDashboardExcel(report: DashboardReportData, meta: ExportMeta) {
  const {
    totals,
    payments,
    paymentsByStatus,
    attendanceStats,
    monthlyRevenue,
    franchiseRevenue,
    supportRequests,
    studentsByStatus,
    filters,
  } = report;

  const title = tabTitle(meta.tab);
  const org = meta.orgName || BRAND.name;
  const statusLabel = meta.statusLabel || titleCase(filters.status || "ALL");
  const paymentSum = payments.reduce((s, p) => s + p.amount, 0);

  const summaryBody: Cell[][] = [
    [BRAND.name, BRAND.fullName],
    ["Report Title", title],
    ["Organization", org],
    ["Date Range", meta.rangeLabel],
    ["Franchise Scope", meta.franchiseLabel],
    ["Payment Status Filter", statusLabel],
    ["Generated By", meta.generatedBy],
    ["Generated At", fmtDateTime()],
    ["", ""],
    ["KEY TOTALS", "VALUE"],
    ["Total Students", totals.totalStudents],
    ["Total Staff", totals.totalStaff],
    ["Total Franchises", totals.totalFranchises],
    ["Active Franchises", totals.activeFranchises],
    ["Filtered Revenue (₹)", moneyPlain(totals.revenue)],
    ["Payment Transactions", totals.paymentCount],
    ["Average Payment (₹)", moneyPlain(totals.avgPayment)],
    ["Pending Fee Students", totals.pendingFees],
    ["Pending Certificates", totals.pendingCertificates],
    ["Attendance Rate (%)", totals.attendancePercent],
    ["Attendance Entries", totals.attendanceTotal],
    ["Support Requests", totals.supportCount],
    ["Course Enquiries", totals.courseEnquiries],
    ["Franchise Inquiries", totals.franchiseInquiries],
    ["Offer Applications", totals.offerApplications],
    ["Total Leads", totals.leadTotal],
    ["", ""],
    ["Listed Payments Total (₹)", moneyPlain(paymentSum)],
  ];

  const paymentRows: Cell[][] = [
    ["#", "Date", "Student Name", "Franchise", "Amount (₹)", "Status"],
    ...payments.map((p, i) => [
      i + 1,
      fmtDate(p.date),
      p.studentName,
      p.franchiseName,
      moneyPlain(p.amount),
      titleCase(p.status),
    ]),
    ["", "", "", "GRAND TOTAL", moneyPlain(paymentSum), ""],
  ];

  const statusRows: Cell[][] = [
    ["Payment Status", "Count", "Amount (₹)", "% of Transactions"],
    ...paymentsByStatus.map((p) => [
      titleCase(p.status),
      p.count,
      moneyPlain(p.amount),
      totals.paymentCount > 0 ? Number(((p.count / totals.paymentCount) * 100).toFixed(1)) : 0,
    ]),
  ];

  const attendanceRows: Cell[][] = [
    ["Attendance Status", "Count", "% Share"],
    ...Object.entries(attendanceStats).map(([k, v]) => [
      titleCase(k),
      v,
      totals.attendanceTotal > 0 ? Number(((v / totals.attendanceTotal) * 100).toFixed(1)) : 0,
    ]),
  ];

  const monthlyRows: Cell[][] = [
    ["Month (YYYY-MM)", "Revenue (₹)"],
    ...monthlyRevenue.map((m) => [m.month, moneyPlain(m.amount)]),
    ["TOTAL", moneyPlain(monthlyRevenue.reduce((s, m) => s + m.amount, 0))],
  ];

  const franchiseRows: Cell[][] = [
    ["#", "Franchise Name", "Transactions", "Revenue (₹)"],
    ...franchiseRevenue.map((f, i) => [i + 1, f.name, f.count, moneyPlain(f.amount)]),
    ["", "TOTAL", franchiseRevenue.reduce((s, f) => s + f.count, 0), moneyPlain(franchiseRevenue.reduce((s, f) => s + f.amount, 0))],
  ];

  const studentRows: Cell[][] = [
    ["Student Status", "Count"],
    ...studentsByStatus.map((s) => [titleCase(s.status), s.count]),
    ["TOTAL", studentsByStatus.reduce((s, x) => s + x.count, 0)],
  ];

  const supportRows: Cell[][] = [
    ["#", "Date", "Full Name", "Email", "Message"],
    ...supportRequests.map((s, i) => [
      i + 1,
      fmtDate(s.createdAt),
      s.fullName,
      s.email,
      s.message.replace(/\s+/g, " ").slice(0, 250),
    ]),
  ];

  const sheet = (name: string, rows: Cell[][], headerStyleRows = [0]) => {
    const xmlRows = rows
      .map((r, idx) => {
        if (headerStyleRows.includes(idx)) {
          return rowXml(r, r.map(() => "Header"));
        }
        // Highlight TOTAL rows
        const joined = r.map(String).join(" ").toUpperCase();
        if (joined.includes("GRAND TOTAL") || joined.includes("TOTAL") || joined.includes("KEY TOTALS")) {
          return rowXml(r, r.map(() => "Total"));
        }
        return rowXml(r, idx % 2 === 0 ? r.map(() => "Alt") : undefined);
      })
      .join("");
    return `<Worksheet ss:Name="${escapeXml(name)}"><Table>${xmlRows}</Table></Worksheet>`;
  };

  const coverRows: Cell[][] = [
    [BRAND.name],
    [BRAND.fullName],
    [title],
    [""],
    ["Report Period", meta.rangeLabel],
    ["Franchise", meta.franchiseLabel],
    ["Status Filter", statusLabel],
    ["Prepared By", meta.generatedBy],
    ["Prepared On", fmtDateTime()],
    [""],
    ["Notes"],
    ["1. All amounts are in Indian Rupees (INR)."],
    ["2. Totals reflect the selected filters (date range, franchise, payment status)."],
    ["3. Sheets: Summary, Payments, Payment Status, Attendance, Monthly Revenue, Franchise Revenue, Students, Support."],
  ];

  const xml = `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
  <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
    <Title>${escapeXml(`${org} — ${title}`)}</Title>
    <Subject>${escapeXml(meta.rangeLabel)}</Subject>
    <Author>${escapeXml(meta.generatedBy)}</Author>
    <Company>${escapeXml(BRAND.fullName)}</Company>
  </DocumentProperties>
  <Styles>
    <Style ss:ID="Default"><Font ss:FontName="Calibri" ss:Size="11"/></Style>
    <Style ss:ID="Header">
      <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#FFFFFF"/>
      <Interior ss:Color="${BRAND.primary}" ss:Pattern="Solid"/>
      <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
    </Style>
    <Style ss:ID="Total">
      <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1"/>
      <Interior ss:Color="#FEF3C7" ss:Pattern="Solid"/>
    </Style>
    <Style ss:ID="Alt">
      <Interior ss:Color="#F8FAFC" ss:Pattern="Solid"/>
    </Style>
    <Style ss:ID="Title">
      <Font ss:FontName="Calibri" ss:Size="16" ss:Bold="1" ss:Color="${BRAND.primary}"/>
    </Style>
  </Styles>
  ${sheet("Cover", coverRows, [0, 1, 2, 10])}
  ${sheet("Summary", summaryBody, [0, 9])}
  ${sheet("Payments", paymentRows, [0])}
  ${sheet("Payment Status", statusRows, [0])}
  ${sheet("Attendance", attendanceRows, [0])}
  ${sheet("Monthly Revenue", monthlyRows, [0])}
  ${sheet("Franchise Revenue", franchiseRows, [0])}
  ${sheet("Students", studentRows, [0])}
  ${sheet("Support", supportRows, [0])}
</Workbook>`;

  return Buffer.from(xml, "utf-8");
}

/** Professional branded PDF with logo, headers, tables & accurate totals */
export async function buildDashboardPdf(report: DashboardReportData, meta: ExportMeta): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 40,
      size: "A4",
      info: {
        Title: `${BRAND.name} — ${tabTitle(meta.tab)}`,
        Author: meta.generatedBy,
        Subject: `${meta.rangeLabel} · ${meta.franchiseLabel}`,
        Creator: BRAND.fullName,
      },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const left = 40;
    const right = pageWidth - 40;
    const contentW = right - left;

    const { totals, payments, paymentsByStatus, monthlyRevenue, franchiseRevenue, studentsByStatus, attendanceStats, supportRequests, filters } =
      report;
    const title = tabTitle(meta.tab);
    const statusLabel = meta.statusLabel || titleCase(filters.status || "ALL");
    const paymentSum = payments.reduce((s, p) => s + p.amount, 0);
    const logoPath = resolveLogoPath();

    const drawFooter = () => {
      const footerY = doc.page.height - 28;
      doc.save();
      doc.moveTo(left, footerY - 8).lineTo(right, footerY - 8).strokeColor(BRAND.border).lineWidth(0.5).stroke();
      doc.font("Helvetica").fontSize(7).fillColor(BRAND.muted);
      doc.text(`${BRAND.name} · Confidential Dashboard Report`, left, footerY - 2, {
        width: contentW * 0.55,
        align: "left",
      });
      doc.text(fmtDateTime(), left, footerY - 2, { width: contentW, align: "right" });
      doc.restore();
    };

    // —— Header band ——
    doc.rect(0, 0, pageWidth, 92).fill(BRAND.primary);

    if (logoPath) {
      try {
        doc.image(logoPath, left, 14, { width: 56, height: 56 });
      } catch {
        // ignore logo load errors
      }
    }

    const textLeft = logoPath ? left + 70 : left;
    doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(16).text(BRAND.name, textLeft, 18, {
      width: contentW - (logoPath ? 70 : 0),
    });
    doc.font("Helvetica").fontSize(8).fillColor("#D6E4F5").text(BRAND.fullName, textLeft, 40, {
      width: contentW - (logoPath ? 70 : 0),
    });
    doc.font("Helvetica-Bold").fontSize(11).fillColor(BRAND.gold).text(title, textLeft, 58, {
      width: contentW - (logoPath ? 70 : 0),
    });

    // Gold accent line
    doc.rect(0, 92, pageWidth, 4).fill(BRAND.gold);

    let y = 112;

    // Meta box
    doc.roundedRect(left, y, contentW, 54, 6).fillAndStroke(BRAND.soft, BRAND.border);
    doc.fillColor("#0F172A").font("Helvetica").fontSize(8);
    const metaLines = [
      `Period: ${meta.rangeLabel}`,
      `Franchise: ${meta.franchiseLabel}`,
      `Payment Status: ${statusLabel}`,
      `Prepared by: ${meta.generatedBy}  ·  ${fmtDateTime()}`,
    ];
    metaLines.forEach((line, i) => {
      doc.text(line, left + 10, y + 8 + i * 11, { width: contentW - 20 });
    });
    y += 68;

    const ensureSpace = (need: number) => {
      if (y + need > doc.page.height - 50) {
        drawFooter();
        doc.addPage();
        y = 40;
      }
    };

    const sectionTitle = (label: string) => {
      ensureSpace(28);
      doc.font("Helvetica-Bold").fontSize(11).fillColor(BRAND.primary).text(label, left, y);
      y += 16;
      doc.moveTo(left, y).lineTo(right, y).strokeColor(BRAND.gold).lineWidth(1).stroke();
      y += 10;
    };

    // KPI grid
    sectionTitle("Key Performance Summary");
    const kpis: [string, string][] = [
      ["Total Students", String(totals.totalStudents)],
      ["Total Staff", String(totals.totalStaff)],
      ["Franchises", `${totals.totalFranchises} (${totals.activeFranchises} active)`],
      ["Filtered Revenue", money(totals.revenue)],
      ["Transactions", String(totals.paymentCount)],
      ["Average Payment", money(totals.avgPayment)],
      ["Pending Fees", String(totals.pendingFees)],
      ["Pending Certificates", String(totals.pendingCertificates)],
      ["Attendance Rate", `${totals.attendancePercent}%`],
      ["Attendance Entries", String(totals.attendanceTotal)],
      ["Total Leads", String(totals.leadTotal)],
      ["Support Requests", String(totals.supportCount)],
    ];

    const colW = contentW / 3 - 6;
    kpis.forEach((kpi, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      if (col === 0) ensureSpace(42);
      const x = left + col * (colW + 9);
      const boxY = y + row * 40;
      doc.roundedRect(x, boxY, colW, 34, 4).fillAndStroke("#FFFFFF", BRAND.border);
      doc.font("Helvetica").fontSize(7).fillColor(BRAND.muted).text(kpi[0], x + 8, boxY + 6, { width: colW - 16 });
      doc.font("Helvetica-Bold").fontSize(10).fillColor(BRAND.primary).text(kpi[1], x + 8, boxY + 17, { width: colW - 16 });
    });
    y += Math.ceil(kpis.length / 3) * 40 + 8;

    // Leads breakdown
    sectionTitle("Lead Pipeline");
    ensureSpace(40);
    doc.font("Helvetica").fontSize(9).fillColor("#1E293B");
    doc.text(
      `Course Enquiries: ${totals.courseEnquiries}    ·    Franchise Inquiries: ${totals.franchiseInquiries}    ·    Offer Applications: ${totals.offerApplications}`,
      left,
      y,
      { width: contentW }
    );
    y += 22;

    // Payment status table
    sectionTitle("Payments by Status");
    const drawTable = (
      headers: string[],
      rows: string[][],
      widths: number[]
    ) => {
      ensureSpace(24);
      let x = left;
      doc.rect(left, y, contentW, 18).fill(BRAND.primary);
      doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(8);
      headers.forEach((h, i) => {
        doc.text(h, x + 4, y + 5, { width: widths[i] - 8 });
        x += widths[i];
      });
      y += 18;

      rows.forEach((row, ri) => {
        ensureSpace(16);
        if (ri % 2 === 0) doc.rect(left, y, contentW, 15).fill("#F8FAFC");
        x = left;
        doc.fillColor("#0F172A").font("Helvetica").fontSize(8);
        row.forEach((cell, i) => {
          doc.text(cell, x + 4, y + 4, { width: widths[i] - 8 });
          x += widths[i];
        });
        y += 15;
      });
      y += 8;
    };

    drawTable(
      ["Status", "Count", "Amount", "% Share"],
      paymentsByStatus.map((p) => [
        titleCase(p.status),
        String(p.count),
        money(p.amount),
        totals.paymentCount > 0 ? `${((p.count / totals.paymentCount) * 100).toFixed(1)}%` : "0%",
      ]),
      [contentW * 0.28, contentW * 0.18, contentW * 0.32, contentW * 0.22]
    );

    if (Object.keys(attendanceStats).length) {
      sectionTitle("Attendance Breakdown");
      drawTable(
        ["Status", "Count", "% Share"],
        Object.entries(attendanceStats).map(([k, v]) => [
          titleCase(k),
          String(v),
          totals.attendanceTotal > 0 ? `${((v / totals.attendanceTotal) * 100).toFixed(1)}%` : "0%",
        ]),
        [contentW * 0.4, contentW * 0.3, contentW * 0.3]
      );
    }

    if (monthlyRevenue.length) {
      sectionTitle("Monthly Revenue");
      drawTable(
        ["Month", "Revenue (INR)"],
        [
          ...monthlyRevenue.map((m) => [m.month, money(m.amount)]),
          ["TOTAL", money(monthlyRevenue.reduce((s, m) => s + m.amount, 0))],
        ],
        [contentW * 0.4, contentW * 0.6]
      );
    }

    if (franchiseRevenue.length) {
      sectionTitle("Franchise-wise Revenue (Top)");
      drawTable(
        ["#", "Franchise", "Txn", "Revenue"],
        franchiseRevenue.slice(0, 12).map((f, i) => [
          String(i + 1),
          f.name.slice(0, 28),
          String(f.count),
          money(f.amount),
        ]),
        [contentW * 0.08, contentW * 0.46, contentW * 0.14, contentW * 0.32]
      );
    }

    if (studentsByStatus.length) {
      sectionTitle("Students by Status");
      drawTable(
        ["Status", "Count"],
        studentsByStatus.map((s) => [titleCase(s.status), String(s.count)]),
        [contentW * 0.6, contentW * 0.4]
      );
    }

    // Payment details
    const showCount = Math.min(payments.length, 35);
    sectionTitle(`Payment Details (${showCount} of ${payments.length})`);
    drawTable(
      ["Date", "Student", "Franchise", "Amount", "Status"],
      payments.slice(0, showCount).map((p) => [
        fmtDate(p.date),
        p.studentName.slice(0, 18),
        p.franchiseName.slice(0, 16),
        money(p.amount),
        titleCase(p.status),
      ]),
      [contentW * 0.16, contentW * 0.26, contentW * 0.24, contentW * 0.18, contentW * 0.16]
    );

    ensureSpace(36);
    doc.roundedRect(left, y, contentW, 32, 5).fillAndStroke("#ECFDF5", "#86EFAC");
    doc.font("Helvetica-Bold").fontSize(9).fillColor("#065F46").text(
      `Listed Payments Total: ${money(paymentSum)}     ·     Filtered Revenue Total: ${money(totals.revenue)}`,
      left + 10,
      y + 11,
      { width: contentW - 20, align: "center" }
    );
    y += 44;

    if (supportRequests.length) {
      sectionTitle(`Support Requests (${Math.min(supportRequests.length, 15)} shown)`);
      supportRequests.slice(0, 15).forEach((s) => {
        ensureSpace(36);
        doc.font("Helvetica-Bold").fontSize(8).fillColor(BRAND.primary).text(
          `${s.fullName}  ·  ${s.email}  ·  ${fmtDate(s.createdAt)}`,
          left,
          y,
          { width: contentW }
        );
        y += 12;
        doc.font("Helvetica").fontSize(8).fillColor("#334155").text(s.message.replace(/\s+/g, " ").slice(0, 160), left, y, {
          width: contentW,
        });
        y += 22;
      });
    }

    ensureSpace(40);
    doc.font("Helvetica").fontSize(7).fillColor(BRAND.muted).text(
      "Disclaimer: Figures are generated from live system data for the selected filters. Amounts are in Indian Rupees (INR).",
      left,
      y,
      { width: contentW, align: "center" }
    );

    drawFooter();
    doc.end();
  });
}
